-- DealAtlas migration 0009
-- Private / supply-chain source onboarding. Only clearly licensed sources are enabled.

insert into public.data_sources (
  source_key,
  name,
  source_type,
  access_method,
  base_url,
  api_url,
  licence_name,
  licence_url,
  terms_url,
  reuse_status,
  scraping_permitted,
  enabled,
  schedule_expression,
  rate_limit_per_minute,
  robots_checked_at,
  terms_checked_at,
  compliance_notes
)
values
  (
    'uk-infrastructure-pipeline',
    'UK Infrastructure Pipeline',
    'GOVERNMENT_OPEN_DATA',
    'JSON_API',
    'https://pipeline.nista.grid.civilservice.gov.uk/',
    'https://pipeline.nista.grid.civilservice.gov.uk/_dash-layout',
    'Open Government Licence v3.0',
    'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/',
    'https://www.gov.uk/help/terms-conditions',
    'OPEN_LICENSE',
    false,
    true,
    '0 6 * * *',
    6,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Official NISTA/GOV.UK pipeline of public and privately delivered infrastructure projects. GOV.UK states the full dataset is downloadable. Ingest the dashboard JSON layout payload. Do not scrape HTML. See docs/SOURCE_COMPLIANCE_REPORT.md.'
  ),
  (
    'nicp-govuk-2023',
    'National Infrastructure and Construction Pipeline 2023',
    'GOVERNMENT_OPEN_DATA',
    'CSV',
    'https://www.gov.uk/government/publications/national-infrastructure-and-construction-pipeline-2023',
    'https://assets.publishing.service.gov.uk/media/65bb870e4965c5000de8a362/National_Infrastructure_and_Construction_Pipeline_2023.xlsx',
    'Open Government Licence v3.0',
    'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/',
    'https://www.gov.uk/help/terms-conditions',
    'OPEN_LICENSE',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Official GOV.UK XLSX under OGL. February 2024 snapshot superseded by the live NISTA pipeline. Represented but not scheduled.'
  ),
  (
    'national-highways-contracts-pipeline',
    'National Highways Contracts Pipeline',
    'GOVERNMENT_OPEN_DATA',
    'PDF_LINK_DISCOVERY',
    'https://nationalhighways.co.uk/',
    'https://nationalhighways.co.uk/media/arqkd5zt/national-highways-activity-pipeline.pdf',
    'Open Government Licence v3.0',
    'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/',
    'https://nationalhighways.co.uk/about-us/our-responsibilities/your-information-rights/publication-scheme/',
    'OPEN_LICENSE',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'RIS2 PDF carries an OGL reuse notice. No current machine-readable contracts datasheet was found on 2026-09-14. Do not scrape eSourcing.'
  ),
  (
    'hs2-direct-contract-opportunities',
    'HS2 Direct Contract Opportunities',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.hs2.org.uk/suppliers/direct-contract-opportunities/',
    null,
    null,
    null,
    'https://www.hs2.org.uk/suppliers/direct-contract-opportunities/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Public Excel/HTML lists exist but hs2.org.uk asserts HS2 Ltd copyright without a site-wide OGL. Not automated.'
  ),
  (
    'hs2-indirect-contract-opportunities',
    'HS2 Indirect / Supply-Chain Opportunities',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.hs2.org.uk/suppliers/indirect-contract-opportunities/',
    null,
    null,
    null,
    'https://www.hs2.org.uk/suppliers/indirect-contract-opportunities/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Same copyright reservation as HS2 direct lists. Live applications often require CompeteFor. Not automated.'
  ),
  (
    'network-rail-procurement-pipeline',
    'Network Rail Procurement Pipeline',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.networkrail.co.uk/industry-and-commercial/supply-chain/procurement/',
    null,
    null,
    null,
    'https://www.networkrail.co.uk/industry-and-commercial/supply-chain/procurement/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Pipeline is described as downloadable but no stable public file URL was found. BravoNR is a login portal. Do not scrape or log in.'
  ),
  (
    'competefor',
    'CompeteFor',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.competefor.com/',
    null,
    null,
    null,
    'https://www.competefor.com/terms-and-conditions/',
    'PROHIBITED',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Terms forbid republication except under a syndication agreement and require login. Blocked.'
  ),
  (
    'tideway-competefor',
    'Tideway Supply Chain (CompeteFor)',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.competefor.com/tideway/',
    null,
    null,
    null,
    'https://www.competefor.com/terms-and-conditions/',
    'PROHIBITED',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Tideway supply-chain portal is CompeteFor. Same republication prohibition.'
  ),
  (
    'sizewell-c-jaggaer',
    'Sizewell C Jaggaer Supply Chain',
    'PROCUREMENT_PLATFORM',
    'HTML',
    'https://sizewellcsupplychain.co.uk/',
    null,
    null,
    null,
    'https://sizewellcsupplychain.co.uk/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Jaggaer source-to-contract portal with registration/login. Do not bypass.'
  ),
  (
    'hinkley-point-c-supply-chain',
    'Hinkley Point C Supply Chain',
    'SUPPLY_CHAIN_PLATFORM',
    'HTML',
    'https://www.hinkleysupplychain.co.uk/',
    null,
    null,
    null,
    'https://www.hinkleysupplychain.co.uk/terms-conditions/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Registration/login matching portal. No open reuse licence for listings.'
  ),
  (
    'national-grid-suppliers',
    'National Grid Suppliers',
    'PRIVATE_COMPANY_WEB',
    'HTML',
    'https://www.nationalgrid.com/suppliers/new-suppliers',
    null,
    null,
    null,
    'https://www.nationalgrid.com/suppliers/new-suppliers',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Achilles UVDB, Coupa and Ariba. No public opportunity feed.'
  ),
  (
    'thames-water-capital-pipeline',
    'Thames Water Capital Delivery Pipeline',
    'PRIVATE_COMPANY_WEB',
    'HTML',
    'https://www.thameswater.co.uk/',
    null,
    null,
    null,
    'https://www.thameswater.co.uk/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Indicative pipeline webpage with no reuse licence found. Regulated notices remain available via Find a Tender.'
  ),
  (
    'balfour-beatty-supply-chain',
    'Balfour Beatty Supply Chain',
    'PRIVATE_COMPANY_WEB',
    'HTML',
    'https://www.balfourbeatty.com/',
    null,
    null,
    null,
    'https://www.balfourbeatty.com/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Prime-contractor channel. No clear public reuse licence. Do not log into supplier portals.'
  ),
  (
    'constructionline',
    'Constructionline',
    'PROCUREMENT_PLATFORM',
    'HTML',
    'https://www.constructionline.co.uk/',
    null,
    null,
    null,
    'https://www.constructionline.co.uk/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Commercial supplier-register platform. Not a public open feed.'
  ),
  (
    'achilles-uvdb',
    'Achilles UVDB',
    'PROCUREMENT_PLATFORM',
    'HTML',
    'https://www.achilles.com/',
    null,
    null,
    null,
    'https://www.achilles.com/',
    'UNKNOWN',
    false,
    false,
    null,
    null,
    timestamptz '2026-09-14T00:00:00Z',
    timestamptz '2026-09-14T00:00:00Z',
    'Paid/login qualification database used by utilities. Do not bypass login.'
  )
on conflict (source_key) do update set
  name = excluded.name,
  source_type = excluded.source_type,
  access_method = excluded.access_method,
  base_url = excluded.base_url,
  api_url = excluded.api_url,
  licence_name = excluded.licence_name,
  licence_url = excluded.licence_url,
  terms_url = excluded.terms_url,
  reuse_status = excluded.reuse_status,
  scraping_permitted = excluded.scraping_permitted,
  enabled = excluded.enabled,
  schedule_expression = excluded.schedule_expression,
  rate_limit_per_minute = excluded.rate_limit_per_minute,
  robots_checked_at = excluded.robots_checked_at,
  terms_checked_at = excluded.terms_checked_at,
  compliance_notes = excluded.compliance_notes,
  updated_at = now();
