import type { Metadata } from "next";
import Link from "next/link";

import { AlertCentre } from "@/components/alerts/alert-centre";
import { EmptyState } from "@/components/feedback/empty-state";
import { Heading, Text } from "@/components/layout/heading";
import { Main } from "@/components/layout/container";
import { Button } from "@/components/ui/button";
import { listAlertCentre } from "@/lib/alerts/centre";
import { assertAlertDto } from "@/lib/alerts/dto";
import { isEmailVerified, requireUser } from "@/lib/auth/session";
import { PLANS } from "@/lib/constants";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Alerts",
  robots: { index: false, follow: false },
};

export default async function AlertsPage() {
  const { user } = await requireUser("/app/alerts");
  const centre = await listAlertCentre({ userId: user.id });
  centre.items.forEach((item) => assertAlertDto(item));
  const verified = isEmailVerified(user);

  return (
    <Main className="gap-8">
      <div className="flex flex-col gap-2">
        <Heading>Alert centre</Heading>
        <Text variant="muted" className="max-w-3xl">
          {centre.plan === PLANS.PRO
            ? "Pro alerts include paid details after server entitlement checks. Open an opportunity to act on the source."
            : "Free alerts say that a match or change exists. Buyer identity, original titles, and source links stay locked."}
        </Text>
        <p className="text-sm text-muted-foreground">
          {centre.unreadCount === 1
            ? "1 unread alert."
            : `${centre.unreadCount} unread alerts.`}
        </p>
      </div>
      {!verified ? (
        <p className="text-sm text-muted-foreground">
          Confirm your email to receive email digests. In-app alerts still appear
          here.
        </p>
      ) : null}
      {centre.items.length === 0 ? (
        <EmptyState
          title="No alerts yet"
          description="Save a search or opportunity, then keep your company profile current. Alerts are generated by the evaluation job."
        >
          <Button asChild variant="outline">
            <Link href="/app/settings">Alert preferences</Link>
          </Button>
          <Button asChild>
            <Link href="/app/search">Discover opportunities</Link>
          </Button>
        </EmptyState>
      ) : (
        <AlertCentre centre={centre} />
      )}
    </Main>
  );
}
