import fs from "node:fs";
import path from "node:path";

import { LEAK_GATE_TERMS } from "@/lib/redaction/gate-vocabulary";
import type { LeakFindingCode, LeakScanInput, LeakageRisk } from "@/lib/redaction/scan";

const ROOT = path.resolve(__dirname, "../..");

export const LEAK_GATE_FIXTURE_PATH = path.join(ROOT, "tests/fixtures/leak-gate/cases.json");
export const LEAK_GATE_PARITY_SQL_PATH = path.join(
  ROOT,
  "supabase/tests/database/leak_gate_parity.test.sql",
);

export type LeakGateCase = {
  id: string;
  description: string;
  sqlOnly?: boolean;
  preview: {
    title: string;
    summary: string;
    requirements?: string[];
    tags?: string[];
    slug?: string;
    broadRegion?: string;
  };
  expectRisk: LeakageRisk;
  expectCodes: LeakFindingCode[] | string[];
};

export type LeakGateFixture = {
  world: {
    dealId: string;
    buyer: {
      id: string;
      name: string;
      aliases: string[];
      domain: string;
      postcode: string;
      city: string;
    };
    supplier: { id: string; name: string; role: string };
    unlinkedOrganization: { id: string; name: string };
    deal: {
      sourceTitle: string;
      sourceDescription: string;
      reference: string;
      ocid: string;
      submissionDeadline: string;
      exactLocationText: string;
      valueMaxExVat: number;
    };
  };
  cases: LeakGateCase[];
};

export function loadLeakGateFixture(): LeakGateFixture {
  return JSON.parse(fs.readFileSync(LEAK_GATE_FIXTURE_PATH, "utf8")) as LeakGateFixture;
}

const DEFAULT_SLUG = "winter-road-treatment-vehicles";

export function caseSlug(fixture: LeakGateFixture, testCase: LeakGateCase): string {
  return testCase.preview.slug ?? `${DEFAULT_SLUG}-${fixture.world.dealId.slice(0, 8)}`;
}

export function leakScanInputForCase(
  fixture: LeakGateFixture,
  testCase: LeakGateCase,
): LeakScanInput {
  const { buyer, supplier, unlinkedOrganization, deal } = fixture.world;
  return {
    previewTitle: testCase.preview.title,
    previewSummary: testCase.preview.summary,
    requirementsPreview: testCase.preview.requirements ?? [],
    relevanceTags: testCase.preview.tags ?? [],
    slug: caseSlug(fixture, testCase),
    broadRegion: testCase.preview.broadRegion ?? null,
    sourceTitle: deal.sourceTitle,
    sourceDescription: deal.sourceDescription,
    ocid: deal.ocid,
    reference: deal.reference,
    externalPrimaryId: null,
    sourceUrl: null,
    applicationUrl: null,
    sourceName: null,
    sourceKey: null,
    buyerName: buyer.name,
    buyerAliases: buyer.aliases,
    buyerDomain: buyer.domain,
    buyerEmail: null,
    buyerPhone: null,
    linkedOrganizationNames: [supplier.name],
    organizationNames: [buyer.name, ...buyer.aliases, supplier.name, unlinkedOrganization.name],
    exactValueText: null,
    valueMinExVat: null,
    valueMaxExVat: deal.valueMaxExVat,
    submissionDeadline: deal.submissionDeadline,
    exactLocationText: deal.exactLocationText,
    locationTerms: [buyer.city],
    knownPostcodes: [buyer.postcode],
  };
}

function sqlText(value: string | null | undefined): string {
  if (value == null) {
    return "null";
  }
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlTextArray(values: readonly string[]): string {
  return values.length === 0
    ? "'{}'::text[]"
    : `array[${values.map(sqlText).join(", ")}]::text[]`;
}

function normalizedName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function findingsCall(fixture: LeakGateFixture, testCase: LeakGateCase): string {
  return [
    `${sqlText(fixture.world.dealId)}::uuid`,
    sqlText(caseSlug(fixture, testCase)),
    sqlText(testCase.preview.title),
    sqlText(testCase.preview.summary),
    `${sqlText(JSON.stringify(testCase.preview.requirements ?? []))}::jsonb`,
    sqlTextArray(testCase.preview.tags ?? []),
    sqlText(testCase.preview.broadRegion ?? null),
  ].join(",\n    ");
}

export function renderLeakGateParitySql(
  fixture: LeakGateFixture = loadLeakGateFixture(),
  terms: Record<string, readonly string[]> = LEAK_GATE_TERMS,
): string {
  const { buyer, supplier, unlinkedOrganization, deal, dealId } = fixture.world;
  const termRows = Object.entries(terms).flatMap(([kind, list]) =>
    list.map((term) => `(${sqlText(kind)}, ${sqlText(term)})`),
  );

  const lines: string[] = [
    "-- GENERATED by `npm run db:gen-leak-parity` from tests/fixtures/leak-gate/cases.json.",
    "-- Do not edit by hand. The TypeScript scanner runs the same cases in",
    "-- tests/unit/leak-gate-parity.test.ts. All names and identifiers are synthetic.",
    "begin;",
    "select no_plan();",
    "",
    "select set_eq(",
    "  $$select kind, term from private.leak_gate_terms$$,",
    `  $$values ${termRows.join(", ")}$$,`,
    "  'SQL gate vocabulary matches lib/redaction/gate-vocabulary.ts'",
    ");",
    "",
    "insert into public.organizations (id, canonical_name, normalized_name, domain, postcode, city) values",
    `  (${sqlText(buyer.id)}, ${sqlText(buyer.name)}, ${sqlText(normalizedName(buyer.name))}, ${sqlText(buyer.domain)}, ${sqlText(buyer.postcode)}, ${sqlText(buyer.city)}),`,
    `  (${sqlText(supplier.id)}, ${sqlText(supplier.name)}, ${sqlText(normalizedName(supplier.name))}, null, null, null),`,
    `  (${sqlText(unlinkedOrganization.id)}, ${sqlText(unlinkedOrganization.name)}, ${sqlText(normalizedName(unlinkedOrganization.name))}, null, null, null);`,
    "",
  ];

  for (const alias of buyer.aliases) {
    lines.push(
      "insert into public.organization_aliases (organization_id, alias, normalized_alias) values",
      `  (${sqlText(buyer.id)}, ${sqlText(alias)}, ${sqlText(normalizedName(alias))});`,
    );
  }

  lines.push(
    "",
    "insert into public.deals (",
    "  id, source_title, source_description, buyer_organization_id, reference, ocid,",
    "  deal_type, buyer_sector, stage, status, submission_deadline, exact_location_text, value_max_ex_vat",
    ") values (",
    `  ${sqlText(dealId)}, ${sqlText(deal.sourceTitle)}, ${sqlText(deal.sourceDescription)},`,
    `  ${sqlText(buyer.id)}, ${sqlText(deal.reference)}, ${sqlText(deal.ocid)},`,
    "  'PUBLIC_TENDER', 'PUBLIC', 'LIVE', 'OPEN',",
    `  ${sqlText(deal.submissionDeadline)}, ${sqlText(deal.exactLocationText)}, ${deal.valueMaxExVat}`,
    ");",
    "",
    "insert into public.deal_organizations (deal_id, organization_id, role) values",
    `  (${sqlText(dealId)}, ${sqlText(supplier.id)}, ${sqlText(supplier.role)});`,
  );

  for (const testCase of fixture.cases) {
    const call = findingsCall(fixture, testCase);
    lines.push(
      "",
      `-- ${testCase.id}: ${testCase.description}`,
      "select is(",
      `  (select private.detect_preview_leakage(\n    ${call}\n  )::text),`,
      `  ${sqlText(testCase.expectRisk)},`,
      `  ${sqlText(`${testCase.id}: risk is ${testCase.expectRisk}`)}`,
      ");",
    );
    if (testCase.expectCodes.length > 0) {
      lines.push(
        "select ok(",
        `  (select coalesce(array_agg(distinct f.finding_code), '{}') from private.preview_leak_findings(\n    ${call}\n  ) f) @> ${sqlTextArray(testCase.expectCodes as string[])},`,
        `  ${sqlText(`${testCase.id}: reports ${testCase.expectCodes.join(", ")}`)}`,
        ");",
      );
    }
  }

  lines.push("", "select * from finish();", "rollback;", "");
  return lines.join("\n");
}
